### ISSUE TITLE
sci-hub的名称写错了

### ISSUE THREAD

**Issue by jihu9** [zhaoolee/ins#4]
是sci-hub.se
不是ci-hub.se

**Comment by zhaoolee** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/15868458/206835467-dc97c4ab-98f1-4e94-a8f7-eec30b424bd0.png">
这段是程序自动生成的，生成的程序有点小bug, 现在修复了，已经可以正常显示，感谢提醒！
